url: https://penn-price-lab.github.io/
baseurl: mw-pl
destination: ./docs
# Site settings
title: Mutinous Women
email: your-email@domain.com
description: "The secret history of the rebellious Frenchwomen who were exiled to colonial Louisiana and found power in the Mississippi Valley."


# Team names, titles and social links
people:
- name: Pauline Carbonnel
  

- name: Cassandra Hradil 
  



